version: '3.8'

services:
  nest-app:
    image: node:18
    container_name: nest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '8001:8001'
    env_file:
      - .env
    depends_on:
      - postgres
    command: ['yarn', 'run', 'start:dev']

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
